[package]
name = "kayton"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.60.2", features = [
    "Win32",
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_IO",
    "Win32_Storage",
    "Win32_Storage_FileSystem"
] }
